# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    tags: [v*.*.*]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - run: echo "its modified"
    - uses: actions/checkout@v3
      with:
         fetch-depth: 0

    - name: Get current branch
      id: check_step
      run: |
        raw=$(git branch -r --contains ${{ github.ref }})
        branch=${raw##*/}
        echo "branch_name=yellow" >> $GITHUB_ENV
        echo "Branch is ${{ env.branch_name }}."
        echo "ref is ${{ github.event.base_ref }}"
